#include <stdint.h>
#include <stdbool.h>

enum key_codes
{
    KEYCODE_NONE = 0,

    // numeric
    KEYCODE_0,
    KEYCODE_1,
    KEYCODE_2,
    KEYCODE_3,
    KEYCODE_4,
    KEYCODE_5,
    KEYCODE_6,
    KEYCODE_7,
    KEYCODE_8,
    KEYCODE_9,

    // Alphabet
    KEYCODE_A,
    KEYCODE_B,
    KEYCODE_C,
    KEYCODE_D,
    KEYCODE_E,
    KEYCODE_F,
    KEYCODE_G,
    KEYCODE_H,
    KEYCODE_I,
    KEYCODE_J,
    KEYCODE_K,
    KEYCODE_L,
    KEYCODE_M,
    KEYCODE_N,
    KEYCODE_O,
    KEYCODE_P,
    KEYCODE_Q,
    KEYCODE_R,
    KEYCODE_S,
    KEYCODE_T,
    KEYCODE_U,
    KEYCODE_V,
    KEYCODE_W,
    KEYCODE_X,
    KEYCODE_Y,
    KEYCODE_Z,

    // symbols
    KEYCODE_MINUS,
    KEYCODE_EQUAL,
    KEYCODE_BACKTICK,
    KEYCODE_BACKSLASH,
    KEYCODE_BRACKET_LEFT,
    KEYCODE_BRACKET_RIGHT,
    KEYCODE_SEMICOLON,
    KEYCODE_APOSTROPHE,
    KEYCODE_COMMA,
    KEYCODE_DOT,
    KEYCODE_SLASH,

    // modifiers
    KEYCODE_SHIFT_LEFT,
    KEYCODE_SHIFT_RIGHT,
    KEYCODE_CTRL_LEFT,
    KEYCODE_CTRL_RIGHT,
    KEYCODE_ALT_LEFT,
    KEYCODE_ALT_RIGHT,
    KEYCODE_WIN_LEFT,
    KEYCODE_WIN_RIGHT,
    KEYCODE_MENU,
    KEYCODE_CAPS,
    KEYCODE_NUMLOCK,
    KEYCODE_SCROLLLOCK,
 
    // moving
    KEYCODE_ENTER,
    KEYCODE_BACKSPACE,
    KEYCODE_TAB,
    KEYCODE_SPACE,
    KEYCODE_ESCAPE,
    KEYCODE_INSERT,
    KEYCODE_DELETE,
    KEYCODE_HOME,
    KEYCODE_END,
    KEYCODE_PAGE_UP,
    KEYCODE_PAGE_DOWN,
    KEYCODE_ARROW_LEFT,
    KEYCODE_ARROW_RIGHT,
    KEYCODE_ARROW_UP,
    KEYCODE_ARROW_DOWN,
    // functions
    KEYCODE_F1,
    KEYCODE_F2,
    KEYCODE_F3,
    KEYCODE_F4,
    KEYCODE_F5,
    KEYCODE_F6,
    KEYCODE_F7,
    KEYCODE_F8,
    KEYCODE_F9,
    KEYCODE_F10,
    KEYCODE_F11,
    KEYCODE_F12,

    // numpad
    KEYCODE_NUMPAD_0,
    KEYCODE_NUMPAD_1,
    KEYCODE_NUMPAD_2,
    KEYCODE_NUMPAD_3,
    KEYCODE_NUMPAD_4,
    KEYCODE_NUMPAD_5,
    KEYCODE_NUMPAD_6,
    KEYCODE_NUMPAD_7,
    KEYCODE_NUMPAD_8,
    KEYCODE_NUMPAD_9,
    KEYCODE_NUMPAD_PLUS,
    KEYCODE_NUMPAD_MINUS,
    KEYCODE_NUMPAD_STAR,
    KEYCODE_NUMPAD_SLASH,
    KEYCODE_NUMPAD_DOT,
    KEYCODE_NUMPAD_ENTER,
};

typedef struct raw_key_event {
    uint16_t code;        // keycode
    bool pressed;         // true = pressed, false = released
} raw_key_event_t;

typedef void (*key_event_cb_t)(raw_key_event_t event);

void init_keyboard(key_event_cb_t callback);